- name: Create LXC container
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create container
      community.proxmox.proxmox:                      # correct community extension
        api_host: "{{ api_proxmox }}"
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        node: "{{ node }}"
        vmid: "{{ vmid }}"
        hostname: "{{ hostname }}"
        ostemplate: "{{ path }}"                      # base iso for lxc
        cores: "{{ cores }}"
        memory: "{{ memory }}"
        netif:
          net0: name=eth0,bridge=vmbr1,ip=182.17.1.51/16,gw=182.17.1.1
        storage: "{{ storage }}"
        state: present                                # status system(latest - download&update, present - download, absent - delete)
        pubkey: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
        timeout: 900
