lxc_containers:
## Telegram Bot LXC
  - vmid: 802
    hostname: "telegram-lxc"
    cores: 4
    memory: 2048
    ip: 182.17.1.53

## Telegram Jenkins LXC
  - vmid: 801
    hostname: "jenkins-lxc"
    cores: 2
    memory: 2048
    ip: 182.17.1.51

## Nginx LXC
  - vmid: 803
    hostname: "nginx-lxc"
    cores: 2
    memory: 2048
    ip: 182.17.1.54

## Postgresql LXC
  - vmid: 804
    hostname: "postgresql-lxc"
    cores: 2
    memory: 2048
    ip: 182.17.1.52
