## Proxmox creds
api_proxmox: "192.168.1.130"
api_user: "ansible@pve"
api_token_id: "tokenansible"
api_token_secret: "2e056ed9-d600-4526-8246-600956238b91"
node: "pve"
path: "local:vztmpl/debian-13-standard_13.1-2_amd64.tar.zst"
storage: "local-lvm"
bridge: vmbr1
cidr: 16
gateway: 182.17.1.1
## Jenkins LXC
jvmid: 801
jhostname: "jenkins-lxc"
jcores: 2
jip: 182.17.1.51
jmemory: 2048
jpassword: "sroot123"
# Jenkins creds
jenkins_login: "ansible_jenkins"
jenkins_password: "automatic"
jenkins_url: "http://182.17.1.51:8080"

#====================================================================
#####################################################################
#====================================================================
## Telegram Bot LXC
tvmid: 802
thostname: "telegram-lxc"
tcores: 4
tmemory: 2048
tpassword: "sroot123"
tip: 182.17.1.52
# Creds 
#====================================================================
#####################################################################
#====================================================================
## Postgresql LXC
pvmid: 801
phostname: "jenkins-lxc"
pcores: 2
pmemory: 2048
ppassword: "sroot123"
pip: 182.17.1.52
# Postgresql creds
#====================================================================
#####################################################################
#====================================================================
## Nginx LXC
nvmid: 801
nhostname: "jenkins-lxc"
ncores: 2
nmemory: 2048
npassword: "sroot123"
