- name: Create multiple LXC
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create containers
      community.general.proxmox:
        api_host: "{{ api_proxmox }}"
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        node: "{{ node }}"
        vmid: "{{ item.vmid }}"
        hostname: "{{ item.hostname }}"
        ostemplate: "{{ path }}"
        cores: "{{ item.cores }}"
        memory: "{{ item.memory }}"
        netif:
          net0: "name=eth0,bridge={{ item.bridge }},ip={{ item.ip }}/16,gw=182.17.1.1"
        storage: "{{ storage }}"
        state: present
      loop: "{{ lxc_containers }}"