[proxmox]
192.168.1.130 ansible_user=root

[jenkins]
jenkins-lxc 182.17.1.51 ansible_user=root

[postgresql]
db-lxc 182.17.1.52 ansible_user=root

[bot]
telegram-lxc 182.17.1.53 ansible_user=root

[nginx]
nginx-lxc 182.17.1.54 ansible_user=root