[proxmox]
pve ansible_host=192.168.1.130 ansible_user=ansible

[jenkins]
jenkins-lxc ansible_host=182.17.1.51 ansible_user=root

[postgresql]
db-lxc ansible_host=182.17.1.52 ansible_user=root ansible_ssh_common_args='-o StrictHostKeyChecking=no' # disable  WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!

[telegram]
telegram-lxc ansible_host=182.17.1.53 ansible_user=root ansible_ssh_common_args='-o StrictHostKeyChecking=no' # disable  WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!

[nginx]
nginx-lxc ansible_host=182.17.1.54 ansible_user=root