api_token_id: "tokenansible"
api_token_secret: "2e056ed9-d600-4526-8246-600956238b91"
tpassword: "sroot123" # pass LXC telegram
jpassword: "sroot123" # pass LXC jenkins
ppassword: "sroot123" # pass LXC Postgresql
jenkins_password: "automatic"
