- name: Create LXC container
  community.proxmox.proxmox:                      # correct community extension
    api_host: "{{ api_proxmox }}"
    api_user: "{{ api_user }}"
    api_token_id: "{{ api_token_id }}"
    api_token_secret: "{{ api_token_secret }}"
    node: "{{ node }}"
    vmid: "{{ tvmid }}"
    hostname: "{{ thostname }}"
    ostemplate: "{{ path }}"                      # base iso for lxc
    cores: "{{ tcores }}"
    memory: "{{ tmemory }}"
    netif:
      net0: name=eth0,bridge={{ bridge }},ip={{ tip }}/{{ cidr }},gw={{ gateway }}
    features:
      - nesting=1 # virtualization
      - keyctl=1 
    unprivileged: false
    storage: "{{ storage }}"
    state: present                                # status system(latest - download&update, present - download, absent - delete)
    ssh_public_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
    timeout: 900
