- name: Create LXC
  hosts: localhost
  roles: 
    - lxc

- name: Wait for SSH
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait for containers
      wait_for:
        host: "{{ item.ip }}"
        port: 22
        timeout: 120
      loop: "{{ lxc_containers }}"

- name: Configure Bot
  hosts: telegram-lxc
  roles:
    - bot

- name: Configure Postgresql
  hosts: db-lxc
  roles:
    - postgresql
    
# - name: Configure Jenkins
#   hosts: jenkins_lxc

# - name: Configure Postgresql
#   hosts: db_lxc

# - name: Configure Nginx
#   hosts: nginx_lxc


