- name: Create LXC Bot
  hosts: localhost
  roles: 
    - lxc

- name: Configure Bot
  hosts: telegram-lxc

# - name: Configure Jenkins
#   hosts: jenkins_lxc

# - name: Configure Postgresql
#   hosts: db_lxc

# - name: Configure Nginx
#   hosts: nginx_lxc


