api_token_id: "tokenansible"
api_token_secret: "2e056ed9-d600-4526-8246-600956238b91"
telegram_lxc_password: "sroot123" # pass LXC telegram
jenkins_lxc_password: "sroot123" # pass LXC jenkins
db_lxc_password: "sroot123" # pass LXC Postgresql
# jenkins_password: "automatic"
